version: 2
jobs:
    build:
        docker:
            - image: circleci/php:7.4-apache-node-browsers

        steps:
            - checkout

            - run: sudo apt update && sudo apt install -y libsqlite3-dev zlib1g-dev
            - run: sudo docker-php-ext-install zip
            - run: sudo composer self-update

            - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
                keys:
                    - composer-v1-{{ checksum "composer.lock" }}
                    # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
                    - composer-v1-
            - run: composer install -n --optimize-autoloader --classmap-authoritative
            - run: composer dump-autoload --optimize --classmap-authoritative
            - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
                key: composer-v1-{{ checksum "composer.lock" }}
                paths:
                    - vendor

            - restore_cache:
                keys:
                    - node-v1-{{ checksum "package-lock.json" }}
                    - node-v1-
            - run: npm install
            - run: npm run build
            - save_cache:
                key: node-v1-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules

            - run: vendor/bin/phpcs
            - run: vendor/bin/phpcbf
            - run: vendor/bin/phpstan analyse src
            - run: vendor/bin/phpmd src xml phpmd.xml

            - run: php bin/console doctrine:database:create --env=test
            - run: php bin/console doctrine:schema:update --env=test --force
            - run: php bin/console doctrine:fixtures:load -n --env=test
            - run: php bin/phpunit


